# Generated by Django 5.0.4 on 2024-04-24 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_facility_secret'),
        ('zone', '0003_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='facility',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.facility'),
        ),
    ]
