# Generated by Django 5.0.4 on 2024-04-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problem', '0004_solution_date'),
        ('zone', '0003_comment_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=10)),
                ('post', models.ManyToManyField(to='zone.post')),
                ('problems', models.ManyToManyField(to='problem.problem')),
            ],
        ),
    ]
