# Generated by Django 5.0.4 on 2024-04-17 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0003_usertagweight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertagweight',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tag.tag'),
        ),
    ]
