# Generated by Django 4.2.7 on 2024-04-03 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_problem_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='problem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='problem.problem'),
            preserve_default=False,
        ),
    ]
