# Generated by Django 4.2.7 on 2024-04-03 11:44

from django.db import migrations, models
import problem.models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0003_solution_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='date',
            field=models.DateTimeField(default=problem.models.now),
        ),
    ]
