# Generated by Django 5.0.4 on 2024-04-11 13:25

import problem.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0004_solution_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='date',
            field=models.DateTimeField(default=problem.models.now),
        ),
    ]
