# Generated by Django 4.2.11 on 2024-04-03 15:05

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='user/avatar/default_avatar.jpg', upload_to=user.models.Rename('user/avatar/'), verbose_name='avatar'),
        ),
    ]
