# Generated by Django 5.0.4 on 2024-04-12 03:45

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='secret',
            field=models.CharField(default=user.models.new_secret, max_length=16),
        ),
    ]
