# Generated by Django 5.0.4 on 2024-04-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0003_alter_slidegeneration_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidegeneration',
            name='status',
            field=models.CharField(default='pending', max_length=16),
        ),
    ]
