# Generated by Django 5.0.4 on 2024-04-12 06:38

import AI.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0005_alter_slidegeneration_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidegeneration',
            name='cover',
            field=models.ImageField(null=True, upload_to=AI.models.Rename('ai/slides/cover/')),
        ),
    ]
